"""
Tourist safety chat assistant. Grounds every answer in real zone/incident
data pulled fresh from MongoDB — the LLM never invents risk levels or
zone names. "Safest zones" is always computed server-side from actual
risk labels, never left to the model to guess or hallucinate.
"""

import re

from groq import Groq

from app.config import settings
from app.services.zone_service import zone_service

_client: Groq | None = None


def get_groq_client() -> Groq:
    global _client
    if _client is None:
        if not settings.groq_api_key:
            raise RuntimeError(
                "GROQ_API_KEY is not set. Add it to your .env file to enable the chat assistant."
            )
        _client = Groq(api_key=settings.groq_api_key)
    return _client


RISK_RANK = {
    "Insufficient Data": 0,
    "LOW": 1,
    "MEDIUM": 2,
    "HIGH": 3,
    "VERY HIGH": 4,
}


def _sort_key(zone: dict):
    label = zone["crime_score"]["risk_label"]
    return (RISK_RANK.get(label, 0), zone["crime_score"]["total_incidents"])


def build_zone_context(zones: list[dict]) -> str:
    """Compact, LLM-readable summary of every zone's real current stats."""
    lines = []
    for zone in zones:
        score = zone["crime_score"]
        categories = ", ".join(score.get("category_breakdown", {}).keys()) or "none recorded"
        lines.append(
            f"- {zone['name']}: risk={score['risk_label']}, "
            f"incidents={score['total_incidents']}, categories=[{categories}]"
        )
    return "\n".join(lines)


def compute_safest_zones(zones: list[dict], limit: int = 3) -> list[dict]:
    """Real, deterministic ranking — never generated by the LLM."""
    # Only rank zones with actual data; "Insufficient Data" zones are
    # excluded here since we can't honestly call them "safest" — there's
    # just nothing recorded, which isn't the same as verified-safe.
    ranked = [z for z in zones if z["crime_score"]["total_incidents"] > 0]
    ranked.sort(key=_sort_key)
    return ranked[:limit]


def find_mentioned_zones(answer_text: str, zones: list[dict]) -> list[dict]:
    """Zones the LLM's answer actually named, so the frontend can render
    clickable chips for exactly those — not a guess, a text match against
    real zone names."""
    mentioned = []
    lower_answer = answer_text.lower()
    for zone in zones:
        # word-boundary match so "Ongole" doesn't match everything
        if re.search(re.escape(zone["name"].lower()), lower_answer):
            mentioned.append(zone)
    return mentioned


def zone_summary(zone: dict) -> dict:
    return {
        "zone_id": zone["zone_id"],
        "name": zone["name"],
        "risk_label": zone["crime_score"]["risk_label"],
        "total_incidents": zone["crime_score"]["total_incidents"],
        "latitude": zone["latitude"],
        "longitude": zone["longitude"],
    }


SYSTEM_PROMPT = """You are a safety assistant for Ongole SafeMap, a tourist safety information app for Ongole, Andhra Pradesh, India.

Rules you must follow:
- Only use the zone data provided below. Never invent crime statistics, zone names, or risk levels that aren't in the data.
- If a zone isn't in the data, say you don't have information about it — don't guess.
- Be concise, calm, and practical. This is safety information for real visitors.
- If asked for the "safest" or "best" area, base your answer strictly on the risk labels given — LOW is safer than MEDIUM, which is safer than HIGH/VERY HIGH.
- "Insufficient Data" zones are not the same as "safe" — say plainly that there isn't enough recorded data to judge them, don't imply safety.
- Do not give medical, legal, or emergency-response advice. For an active emergency, tell the user to contact local police directly.
- Keep answers short — 2-4 sentences unless the user asks for more detail.
"""


async def ask_assistant(question: str) -> dict:
    zones = await zone_service.get_all_zones()
    context = build_zone_context(zones)

    client = get_groq_client()
    completion = client.chat.completions.create(
        model=settings.groq_model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": (
                    f"Current zone data for Ongole:\n{context}\n\n"
                    f"Visitor's question: {question}"
                ),
            },
        ],
        temperature=0.3,
        max_tokens=400,
    )
    answer = completion.choices[0].message.content.strip()

    mentioned = find_mentioned_zones(answer, zones)
    safest = compute_safest_zones(zones)

    return {
        "answer": answer,
        "mentioned_zones": [zone_summary(z) for z in mentioned],
        "safest_zones": [zone_summary(z) for z in safest],
    }